name: Hello World Workflow
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Ekrandan salom yo'llash qadami
      - name: Run a one-line script
        run: echo "Hello, World! Men GitHub Actions-ni o'rganyapman!"

      # 2. GitHub-dagi kodingizni robotning kompyuteriga yuklab olish qadami
      - name: Check out repository code
        uses: actions/checkout@v4

      # 3. Robot ichida Python dasturlash tilini sozlash qadami
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4. Hammasi tayyor bo'lganini bildirish
      - name: Success Message
        run: echo "Ura! Robot hamma ishlarni muvaffaqiyatli bajardi!"